// Usernames that would collide with top-level routes/sections, infra paths,
// future sections, legal pages, and impersonation/safety terms. All lowercase;
// lookups normalize to lowercase.

const RESERVED_LIST = [
  // Live routes
  "about",
  "admin",
  "advertise",
  "alpha",
  "api",
  "articles",
  "company",
  "courses",
  "create",
  "d",
  "draft",
  "feed",
  "get-started",
  "hub",
  "jobs",
  "metrics",
  "my-posts",
  "notifications",
  "saved",
  "settings",
  "speakers",
  "volunteer",
  "welcome",
  "code-of-conduct",

  // Infra / well-known
  "robots.txt",
  "sitemap",
  "sitemap.xml",
  "sitemaps",
  "feed.xml",
  "rss",
  "atom.xml",
  "llms.txt",
  "manifest.json",
  "favicon.ico",
  "ads.txt",
  "security.txt",
  "humans.txt",
  "opensearch.xml",
  "well-known",
  "_next",
  "_vercel",
  "static",
  "assets",
  "images",
  "img",
  "media",
  "cdn",
  "og",

  // Auth / account
  "auth",
  "login",
  "logout",
  "signin",
  "signup",
  "register",
  "oauth",
  "callback",
  "sso",
  "verify",
  "reset",
  "account",
  "me",
  "profile",
  "profiles",
  "user",
  "users",

  // Future sections
  "tag",
  "tags",
  "topic",
  "topics",
  "search",
  "explore",
  "trending",
  "popular",
  "new",
  "top",
  "leaderboard",
  "badges",
  "achievements",
  "collections",
  "series",
  "bookmarks",
  "drafts",
  "dashboard",
  "home",
  "inbox",
  "messages",
  "events",
  "groups",
  "community",
  "communities",
  "teams",
  "orgs",
  "sponsors",
  "partners",
  "learn",
  "guides",
  "docs",
  "help",
  "support",
  "faq",
  "contact",
  "blog",
  "newsletter",
  "press",
  "brand",
  "status",
  "changelog",
  "roadmap",
  "pricing",
  "s",
  "p",
  "c",
  "u",
  "r",
  "t",

  // Legal
  "privacy",
  "terms",
  "tos",
  "legal",
  "cookies",
  "dmca",
  "gdpr",
  "disclaimer",

  // Impersonation / safety
  "codu",
  "official",
  "staff",
  "team",
  "mod",
  "mods",
  "moderator",
  "administrator",
  "root",
  "system",
  "info",
  "noreply",
  "no-reply",
  "anonymous",
  "deleted",
  "null",
  "undefined",
  "everyone",
  "all",
];

const RESERVED = new Set<string>(RESERVED_LIST);

// Reserve every single letter a-z (covers all single-char route prefixes).
for (let code = "a".charCodeAt(0); code <= "z".charCodeAt(0); code += 1) {
  RESERVED.add(String.fromCharCode(code));
}

export function isReservedUsername(name: string): boolean {
  return RESERVED.has(name.trim().toLowerCase());
}
