name: Accessibility Alt Text Bot

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  discussion:
    types: [created, edited]
  discussion_comment:
    types: [created, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number || github.event.pull_request.number || github.event.discussion.number || github.ref }}
  cancel-in-progress: true

permissions:
  issues: write
  pull-requests: write
  discussions: write

jobs:
  accessibility_alt_text_bot:
    name: Check alt text on issues and pull requests
    runs-on: ubuntu-latest
    steps:
      - name: Run Alt Text Bot
        uses: github/accessibility-alt-text-bot@v1.4.0
